# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.hostname = "<%= appDomain %>"
  config.vm.network :private_network, :ip => "192.168.50.4"
  config.hostsupdater.remove_on_suspend = true

  config.vm.synced_folder "./", "/vagrant",
    owner: "www-data", group: "www-data", mount_options: ['dmode=775', 'fmode=775']

  config.vm.provision :shell, path: "provision.sh"

  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    vb.customize ['modifyvm', :id, '--natdnsproxy1', 'on']
  end
end
